# Generated by Django 2.2.14 on 2021-05-13 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sushi_app', '0046_merge_20210308_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mailing/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст рассылки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('files', models.ManyToManyField(related_name='manyfile', to='mailing.FilesMailing', verbose_name='Вложения')),
                ('senders', models.ManyToManyField(related_name='mailings', to='sushi_app.UserProfile', verbose_name='Получатели')),
                ('to_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings', to=settings.AUTH_USER_MODEL, verbose_name='Получатели')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
