# Generated by Django 2.2.2 on 2019-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name': 'Вопрос от пользователя', 'verbose_name_plural': 'Вопросы от пользоватлей'},
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'На рассмотрении'), (1, 'Одобрено'), (2, 'Отклонено')], default=0),
        ),
    ]
