# Generated by Django 2.2.3 on 2020-08-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0024_newspage_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideamodel',
            name='file',
        ),
        migrations.CreateModel(
            name='IdeaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='ideas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mickroservices.IdeaModel')),
            ],
        ),
    ]
