# Generated by Django 2.2.14 on 2020-08-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0025_auto_20200801_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_title', models.CharField(default=None, max_length=255, verbose_name='preview_title')),
                ('preview_file', models.FileField(default=None, upload_to='document_previews', verbose_name='preview_file')),
                ('base_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mickroservices.DocumentSushi')),
            ],
        ),
    ]
