# Generated by Django 2.2.14 on 2021-05-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mickroservices', '0026_documentpreview'),
        ('chat', '0005_auto_20210503_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mickroservices.IdeaModel'),
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mickroservices.QuestionModel'),
        ),
    ]
