# Generated by Django 2.2.3 on 2020-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0036_requests_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ddk_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
