# Generated by Django 2.2.3 on 2020-07-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0037_auto_20200713_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='sing',
            new_name='sign',
        ),
    ]
