# Generated by Django 2.2.3 on 2020-07-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0037_userprofile_ddk_number'),
        ('sushi_app', '0040_auto_20200713_1537'),
    ]

    operations = [
    ]
