# Generated by Django 2.2.3 on 2020-08-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0041_merge_20200719_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='file',
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sushi_app.Requests')),
            ],
        ),
    ]
