# Generated by Django 2.2.14 on 2020-08-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sushi_app', '0042_auto_20200801_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('task', 'Задачи'), ('messege', 'Сообщения'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10)),
                ('subscribe_type', models.CharField(choices=[('task', 'Задачи'), ('messege', 'Сообщения'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_type', models.CharField(choices=[('task', 'Задачи'), ('messege', 'Сообщения'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_events', to='sushi_app.Subscribes')),
            ],
        ),
    ]
