# Generated by Django 2.2.14 on 2020-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sushi_app', '0043_notificationevents_subscribes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к пользователю'),
        ),
    ]
