# Generated by Django 2.2.14 on 2021-03-01 07:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0043_notificationevents_subscribes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sushi_app.Directory')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.AlterField(
            model_name='notificationevents',
            name='event_type',
            field=models.CharField(choices=[('task', 'Задачи от менеджера'), ('request', 'Задачи от франчайзи'), ('messege', 'Сообщения'), ('question', 'Вопросы'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='event_type',
            field=models.CharField(choices=[('task', 'Задачи от менеджера'), ('request', 'Задачи от франчайзи'), ('messege', 'Сообщения'), ('question', 'Вопросы'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='subscribe_type',
            field=models.CharField(choices=[('task', 'Задачи от менеджера'), ('request', 'Задачи от франчайзи'), ('messege', 'Сообщения'), ('question', 'Вопросы'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10),
        ),
        migrations.CreateModel(
            name='DirectoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_file', models.FileField(upload_to='directory_files', verbose_name='Файл')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_files', to='sushi_app.Directory')),
            ],
        ),
    ]
