# Generated by Django 2.2.14 on 2020-10-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0043_notificationevents_subscribes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevents',
            name='event_type',
            field=models.CharField(choices=[('task', 'Задачи от менеджера'), ('request', 'Задачи от франчайзи'), ('messege', 'Сообщения'), ('question', 'Вопросы'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='event_type',
            field=models.CharField(choices=[('task', 'Задачи от менеджера'), ('request', 'Задачи от франчайзи'), ('messege', 'Сообщения'), ('question', 'Вопросы'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscribes',
            name='subscribe_type',
            field=models.CharField(choices=[('task', 'Задачи от менеджера'), ('request', 'Задачи от франчайзи'), ('messege', 'Сообщения'), ('question', 'Вопросы'), ('news', 'Новости'), ('feedback', 'Отзывы'), ('shop', 'Создание магазина'), ('idea', 'Идеи'), ('materials', 'Материалы')], max_length=10),
        ),
    ]
