# Generated by Django 2.2.14 on 2021-03-03 04:52

from django.db import migrations, models
import sushi_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0044_auto_20210301_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryfile',
            name='dir_file',
            field=models.FileField(upload_to=sushi_app.models.get_upload_path, verbose_name='Файл'),
        ),
    ]
