# Generated by Django 2.2.14 on 2021-03-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_app', '0045_userprofile_comment'),
        ('sushi_app', '0045_auto_20210303_0752'),
    ]

    operations = [
    ]
